In [ ]:
import numpy as np

Numpy Arrays
pip install numpy pandas matplotlib searborn
*italicized text*

In [19]:

# Creating a 1D NumPy array
arr1d = np.array([1, 2, 3, 4, 5]) #1D
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                   [7, 8, 9]]) #2D

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# arr2d.shape
# arr2d.ndim
arr2d.size

9

In [26]:
# arr1d[1]
# arr1d[1:3]
# arr2d[1, 2] #indexing
arr2d[0:2, 1:3] #slicing

array([[2, 3],
       [5, 6]])

In [ ]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
addition = a + b
print("\nAddition:", addition)  # [5 7 9]

# Multiplication
multiplication = a * b
print("Multiplication:", multiplication)  # [ 4 10 18]

# Other operations: subtraction (-), division (/), power (**), etc.



Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [ ]:
# Matrix operations
matrix_a = np.array([[1, 2],
                      [3, 4]])
matrix_b = np.array([[5, 6],
                    [7, 8]])

# Matrix multiplication
matrix_mult = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication:")
print(matrix_mult)

# Output:
# Matrix Multiplication:
# [[19 22]
#  [43 50]]

# Transpose of a matrix
matrix_transpose = np.transpose(matrix_a)
print("\nTranspose of Matrix A:")
print(matrix_transpose)

# Output:
# Transpose of Matrix A:
# [[1 3]
#  [2 4]]



Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]


In [ ]:
# Broadcasting with arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result_broadcast = arr1 + arr2

print("\nBroadcasting Arrays:")
print(result_broadcast)

# Output:
# Broadcasting Arrays:
# [[11 22 33]
#  [14 25 36]]


Broadcasting Arrays:
[[11 22 33]
 [14 25 36]]


In [13]:
l = [1,2,3,4,5,6,7]

print([x*x for x in l])

[1, 4, 9, 16, 25, 36, 49]


In [14]:
l[2]

3